package com.app.dao;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "User")
public class UserDao {
	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true)
	int id;

	@DatabaseField
	private String href;
	@DatabaseField
	private String userid;
	@DatabaseField
	private String email;
	@DatabaseField
	private String name;
	@DatabaseField
	private String firstName;
	@DatabaseField
	private String lastName;
	@DatabaseField
	private int type;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getHref() {
		return href;
	}

	public void setHref(String href) {
		this.href = href;
	}

	public UserDao() {
		// all persisted classes must define a no-argument constructor with at
		// least package visibility
	}

	@Override
	public String toString() {
		return "UserDao [id=" + id + ", href=" + href + ", userid=" + userid
				+ ", email=" + email + ", name=" + name + ", firstName="
				+ firstName + ", lastName=" + lastName + ", type=" + type + "]";
	}

}
